#!/usr/bin/env python

import sys

from kafka import ConsoleProducer
from kafka._script_utils import parse_options, get_client

CLIENT_ID = "kp_producer"

def main():
    options = parse_options()
    client = get_client(options.broker, CLIENT_ID)
    producer = ConsoleProducer(client)
    try:
        producer.run(options.topic)
        producer.stop()
    except KeyboardInterrupt:
        producer.stop()
    finally:
        client.close()
    print("Done!")
    return 0

if __name__ == '__main__':
    sys.exit(main())
